-- MySQL Script generated by MySQL Workbench
-- 07/04/24 16:05:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ml
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ml
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ml` DEFAULT CHARACTER SET utf8 ;
USE `ml` ;

-- -----------------------------------------------------
-- Table `ml`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ml`.`product` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `desсription` VARCHAR(1000) NULL DEFAULT NULL,
  `category` VARCHAR(45) NOT NULL,
  `amount` INT(11) NOT NULL,
  `cost` DOUBLE NOT NULL,
  `release_date` INT(11) NOT NULL,
  `raiting` DOUBLE NOT NULL,
  `image` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ml`.`product1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ml`.`product1` (
  `product_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product` VARCHAR(100) NOT NULL,
  `article` VARCHAR(45) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `price` INT(11) NOT NULL,
  `seller` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `subcategory` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ml`.`Manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ml`.`Manufacturer` (
  `manufacturer_id` INT NOT NULL AUTO_INCREMENT,
  `name_manufacturer` VARCHAR(100) NOT NULL,
  `address_manufacturer` VARCHAR(45) NOT NULL,
  `telephone_manufacturer` VARCHAR(45) NOT NULL,
  `email_manufacturer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`manufacturer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ml`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ml`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product` VARCHAR(100) NOT NULL,
  `article` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `manufacturer_id` INT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `mamufacture_idx` (`manufacturer_id` ASC),
  CONSTRAINT `mamufacture`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `ml`.`Manufacturer` (`manufacturer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ml`.`buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ml`.`buyer` (
  `buyer_id` INT NOT NULL AUTO_INCREMENT,
  `name_buyer` VARCHAR(45) NOT NULL,
  `email_buyer` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`buyer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ml`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ml`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(45) NOT NULL,
  `buyer_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `price` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `buyer_idx` (`buyer_id` ASC),
  INDEX `products_idx` (`product_id` ASC),
  CONSTRAINT `buyer`
    FOREIGN KEY (`buyer_id`)
    REFERENCES `ml`.`buyer` (`buyer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `products`
    FOREIGN KEY (`product_id`)
    REFERENCES `ml`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
